#! /bin/bash

# Deployment info
server="toaster.vdeute.com"

# Config file
projectname="webhookproject"
hub_username="wvdeutekom"

#Go
go_containername="go"
go_imagename="latest"
go_hub_repository="go"
declare -a go_ports=(8000:8000)

# Rethinkdb
rethink_containername="rethink"
rethink_imagename="latest"
rethink_hub_repository="rethinkdb"
rethink_datavolume="datavolume-rethink"
declare -a rethink_ports=(28015:28015 29015:29015 8080:8080)
