#! /bin/bash

# Deployment info
deploy_server="toaster.vdeute.com"
deploy_dir="/goquotes"

# Config file
projectname="webhookproject"
hub_username="wvdeutekom"

# Nginx reverse proxy
nginx_containername="nginx_reverseproxy"
nginx_imagename="latest"
ngxinx_hub_reopository="nginx-proxy"
nginx_hub_username="jwilder"
declare -a nginx_port=8000:8000

# Go
go_containername="go"
go_imagename="latest"
go_hub_repository="go"
declare -a go_port=8000:8000

# Rethinkdb
rethink_containername="rethink"
rethink_imagename="latest"
rethink_hub_repository="rethinkdb"
rethink_datavolume="datavolume-rethink"
declare -a rethink_ports=(28015:28015 29015:29015 8080:8080)

# rethink_ports[0]=28015:28015
# rethink_ports[1]=29015:29015
# rethink_ports[2]=8080:8080
